
import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "@/style/globals.css";

import { ChartProvider } from "@/providers/ChartProvider";

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.className} antialiased trancy-zh-CN`}>
        <ChartProvider>
          {children}
        </ChartProvider>
      </body>
    </html>
  );
}
